name: Check rustc_codegen_c Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linux Build Check
      run: |
        rustup install nightly-2024-03-16
        cd compiler/rustc_codegen_c
        cargo +nighlty-2024-03-16 build --release
      
  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Windows Build Check
      run: |
        rustup install nightly-2024-03-16
        cd compiler/rustc_codegen_c
        cargo +nighlty-2024-03-16 build --release
